<a href="https://colab.research.google.com/github/babytejaswi/HELLO-WORLD/blob/main/2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style = "color:Red" >Working with NumPy</h1>


<h2 style = "color:Green"> Outcomes </h2>

#### At the end of this chapter, you will be able to
* Define NumPy data types
* Create and work with NumPy Arrays
* Understand the applications of NumpPy

<h2 style = "color:Green">What is Numpy?</h2>

* A Python package for scientific computations

* NumPy = ***Numerical Python***

* Numpy Library = Multi-dimensional array objects & Functions for processing it.

* Multi-dimensional object --> ___ndarray___ object

* Variaous operations supported: Arithmetic, Logical, Shape manipulation, Sort, DFT, Statistics, Random simulation etc.

* Importing NumPy: ___import numpy as np___

In [ ]:
# import numpy
import numpy as np

<h2 style = "color:Green"> Creating and Accessing ndarray object</h2>
    
* ndarray: Collection of items of the same type

    
* Items can be accessed using zero-based index.

    
* array() Function: ***numpy.array(object)*** 
                --> Creates an ndarray from an object.
                --> object: Any array or sequence.
               

<h3 style = "color:Blue">One Dimensional Array (Vector):</h3>

In [ ]:
# Create an one dimensional ndarray object from a list, display its values and type
n1=np.array([2,3,4,5,6])
print(n1)
print(type(n1))

[2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# Create an one dimensional ndarray object from a tuple, display its values and type
n2=np.array((2.8,3.5,4.9,5.7,6.0))
print(n2)
print(type(n2))

[2.8 3.5 4.9 5.7 6. ]
<class 'numpy.ndarray'>


<h4 style = "color:Brown">Indexing & Slicing:</h4>

![oneDim.png](attachment:oneDim.png)

In [ ]:
# Create above one dimensional ndarray object and access its elements individually. And also slice some of its elements. 
n3=np.array([2,3,4,5,6])
print(n3[0])
print(n3[1])
print(n3[2])
print(n3[3])
print(n3[4])
print(n3[-1])
print(n3[-2])
print(n3[-3])
print(n3[-4])
print(n3[-5])
print(n3[1:3:1])
print(n3[: : -1])

2
3
4
5
6
6
5
4
3
2
[3 4]
[6 5 4 3 2]


<h3 style = "color:Blue">Two-Dimensional Arrays(Matrices)</h3>

* Each element  is itself 1D array


* arr2 = numpy.array([[row1], [row2], ...., [rowM]])


* Accessing an element: arr2[row_index, column_index]

In [ ]:
# Create a two dimensional array and access their rows and columns individually.
# Access the individual elements.
n4=np.array([[1,2,3,4],[5,6,7,8]])
print(n4)
print(type(n4))
print(n4[0][0])
print(n4[0])
print(n4[:1])
print(n4[ : ,1:3])
print(n4[])



[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
1
[1 2 3 4]
[[1 2 3 4]]
[[2 3]
 [6 7]]


<h2 style = "color:Green">ndarray Attribtes</h2>

* ndarray.ndim: Number of dimensions


* ndarry.shape: Array dimensions as a tuple.


* ndarry.size: Total number of elements


* ndarry.dtype: Type of the array elements.


* ndarray.itemsize: The size of each element in bytes

In [ ]:
# Create an one dimensional ndarray object and diplay all its attribute values.
n4=np.array([1,2,3,4,5,6,7])
print(n4)
print(n4.ndim)
print(n4.shape)
print(n4.size)
print(n4.dtype)
print(n4.itemsize)



[1 2 3 4 5 6 7]
1
(7,)
7
int32
4


In [ ]:
# Create a two dimensional ndarray object and diplay all its attribute values.
n4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(n4)
print(n4.ndim)
print(n4.shape)
print(n4.size)
print(n4.dtype)
print(n4.itemsize)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
2
(5, 4)
20
int32
4


<h2 style = "color:Green">Other NumPy array creation functions</h2>

#### zeros(shape)
* Returns an array of zeros with specified shape
* Dafalut dtype is float



#### ones(shape)
* Returns an array of ones with specified shape
* Dafalut dtype is float


#### arange(start, stop, step, dtype)
* Returns an ndarray object with elements decided by start, stop and step arguments.
* Note that stop value is not including in the array.
* Default dtype is type is determined by type of start or stop values.

#### linspace(start, stop, N, dtype)
* Returns an ndarray object with N elements in the range from start value to stop stop .
* Note that stop value is inclusive in the array.
* Defaul type is float64

In [ ]:
# Create ndarray objects with all zeros using different dimensions and dtypes.
n=np.zeros(6,dtype=float)
print(n)




[0. 0. 0. 0. 0. 0.]


In [ ]:
# Create ndarray objects with all ones using different dimensions and dtypes.
n=np.ones(6,dtype=int)
print(n)

[1 1 1 1 1 1]


In [ ]:
# Create one dimensional ndarray objects with various range of values and dtypes.
n4=np.arange(start=1,stop=20,step=5)
print(n4)


[ 1  6 11 16]


In [ ]:
# Create one dimensional ndarray objects with 25 elements between 1 and 100 of different dtypes.
n5=np.linspace(start=1,stop=30,num=5,dtype=float)
print(n5)

[ 1.    8.25 15.5  22.75 30.  ]
